const LEGENDARIES = [
  { name: "Articuno",    id: 144, exclusive: null },
  { name: "Zapdos",     id: 145, exclusive: null },
  { name: "Moltres",    id: 146, exclusive: null },
  { name: "Mewtwo",     id: 150, exclusive: null },
  { name: "Raikou",     id: 243, exclusive: null },
  { name: "Entei",      id: 244, exclusive: null },
  { name: "Suicune",    id: 245, exclusive: null },
  { name: "Lugia",      id: 249, exclusive: "Shield" },
  { name: "Ho-Oh",      id: 250, exclusive: "Sword" },
  { name: "Latias",     id: 380, exclusive: "Shield" },
  { name: "Latios",     id: 381, exclusive: "Sword" },
  { name: "Kyogre",     id: 382, exclusive: "Shield" },
  { name: "Groudon",    id: 383, exclusive: "Sword" },
  { name: "Rayquaza",   id: 384, exclusive: null },
  { name: "Uxie",       id: 480, exclusive: null },
  { name: "Mesprit",    id: 481, exclusive: null },
  { name: "Azelf",      id: 482, exclusive: null },
  { name: "Dialga",     id: 483, exclusive: "Sword" },
  { name: "Palkia",     id: 484, exclusive: "Shield" },
  { name: "Heatran",    id: 485, exclusive: null },
  { name: "Regigigas",  id: 486, exclusive: null },
  { name: "Giratina",   id: 487, exclusive: null },
  { name: "Cresselia",  id: 488, exclusive: null },
  { name: "Tornadus",   id: 641, exclusive: "Sword" },
  { name: "Thundurus",  id: 642, exclusive: "Shield" },
  { name: "Reshiram",   id: 643, exclusive: "Sword" },
  { name: "Zekrom",     id: 644, exclusive: "Shield" },
  { name: "Landorus",   id: 645, exclusive: null },
  { name: "Kyurem",     id: 646, exclusive: null },
  { name: "Xerneas",    id: 716, exclusive: null },
  { name: "Yveltal",    id: 717, exclusive: null },
  { name: "Zygarde",    id: 718, exclusive: null },
  { name: "Tapu Koko",  id: 785, exclusive: null },
  { name: "Tapu Lele",  id: 786, exclusive: null },
  { name: "Tapu Bulu",  id: 787, exclusive: null },
  { name: "Tapu Fini",  id: 788, exclusive: null },
  { name: "Solgaleo",   id: 791, exclusive: "Sword" },
  { name: "Lunala",     id: 792, exclusive: "Shield" },
  { name: "Nihilego",   id: 793, exclusive: null },
  { name: "Buzzwole",   id: 794, exclusive: null },
  { name: "Pheromosa",  id: 795, exclusive: null },
  { name: "Xurkitree",  id: 796, exclusive: null },
  { name: "Celesteela", id: 797, exclusive: null },
  { name: "Kartana",    id: 798, exclusive: null },
  { name: "Guzzlord",   id: 799, exclusive: null },
  { name: "Necrozma",   id: 800, exclusive: null },
  { name: "Stakataka",  id: 805, exclusive: null },
  { name: "Blacephalon",id: 806, exclusive: null },
];

const REGULARS = [
  { name: "Ivysaur",     id: 2 },
  { name: "Charmeleon",  id: 5 },
  { name: "Wartortle",   id: 8 },
  { name: "Butterfree",  id: 12 },
  { name: "Raichu",      id: 26 },
  { name: "Sandslash",   id: 28 },
  { name: "Nidoqueen",   id: 31 },
  { name: "Nidoking",    id: 34 },
  { name: "Clefairy",    id: 35 },
  { name: "Clefable",    id: 36 },
  { name: "Jigglypuff",  id: 39 },
  { name: "Wigglytuff",  id: 40 },
  { name: "Gloom",       id: 44 },
  { name: "Vileplume",   id: 45 },
  { name: "Dugtrio",     id: 51 },
  { name: "Persian",     id: 53 },
  { name: "Golduck",     id: 55 },
  { name: "Poliwrath",   id: 62 },
  { name: "Kadabra",     id: 64 },
  { name: "Machoke",     id: 67 },
  { name: "Tentacruel",  id: 73 },
  { name: "Slowbro",     id: 80 },
  { name: "Magneton",    id: 82 },
  { name: "Haunter",     id: 93 },
  { name: "Kingler",     id: 99 },
  { name: "Exeggutor",   id: 103 },
  { name: "Marowak",     id: 105 },
  { name: "Hitmonlee",   id: 106 },
  { name: "Hitmonchan",  id: 107 },
  { name: "Lickitung",   id: 108 },
  { name: "Weezing",     id: 110 },
  { name: "Rhydon",      id: 112 },
  { name: "Chansey",     id: 113 },
  { name: "Tangela",     id: 114 },
  { name: "Kangaskhan",  id: 115 },
  { name: "Seadra",      id: 117 },
  { name: "Seaking",     id: 119 },
  { name: "Starmie",     id: 121 },
  { name: "Mr. Mime",    id: 122 },
  { name: "Scyther",     id: 123 },
  { name: "Jynx",        id: 124 },
  { name: "Electabuzz",  id: 125 },
  { name: "Magmar",      id: 126 },
  { name: "Tauros",      id: 128 },
  { name: "Ditto",       id: 132 },
  { name: "Vaporeon",    id: 134 },
  { name: "Jolteon",     id: 135 },
  { name: "Flareon",     id: 136 },
  { name: "Porygon",     id: 137 },
  { name: "Dragonair",   id: 148 },
  { name: "Noctowl",     id: 164 },
  { name: "Lanturn",     id: 171 },
  { name: "Togetic",     id: 176 },
  { name: "Xatu",        id: 178 },
  { name: "Bellossom",   id: 182 },
  { name: "Azumarill",   id: 184 },
  { name: "Sudowoodo",   id: 185 },
  { name: "Politoed",    id: 186 },
  { name: "Quagsire",    id: 195 },
  { name: "Slowking",    id: 199 },
  { name: "Dunsparce",   id: 206 },
  { name: "Qwilfish",    id: 211 },
  { name: "Sneasel",     id: 215 },
  { name: "Piloswine",   id: 221 },
  { name: "Octillery",   id: 224 },
  { name: "Mantine",     id: 226 },
  { name: "Skarmory",    id: 227 },
  { name: "Hitmontop",   id: 237 },
  { name: "Miltank",     id: 241 },
  { name: "Grovyle",     id: 253 },
  { name: "Sceptile",    id: 254 },
  { name: "Combusken",   id: 256 },
  { name: "Blaziken",    id: 257 },
  { name: "Marshtomp",   id: 259 },
  { name: "Swampert",    id: 260 },
  { name: "Linoone",     id: 264 },
  { name: "Pelipper",    id: 279 },
  { name: "Ninjask",     id: 291 },
  { name: "Exploud",     id: 295 },
  { name: "Lairon",      id: 305 },
  { name: "Manectric",   id: 310 },
  { name: "Roselia",     id: 315 },
  { name: "Sharpedo",    id: 319 },
  { name: "Wailmer",     id: 320 },
  { name: "Torkoal",     id: 324 },
  { name: "Flygon",      id: 330 },
  { name: "Altaria",     id: 334 },
  { name: "Whiscash",    id: 340 },
  { name: "Crawdaunt",   id: 342 },
  { name: "Claydol",     id: 344 },
  { name: "Cradily",     id: 346 },
  { name: "Armaldo",     id: 348 },
  { name: "Dusclops",    id: 356 },
  { name: "Absol",       id: 359 },
  { name: "Glalie",      id: 362 },
  { name: "Sealeo",      id: 364 },
  { name: "Relicanth",   id: 369 },
  { name: "Metang",      id: 375 },
  { name: "Luxray",      id: 405 },
  { name: "Vespiquen",   id: 416 },
  { name: "Cherrim",     id: 421 },
  { name: "Gastrodon",   id: 423 },
  { name: "Drifblim",    id: 426 },
  { name: "Lopunny",     id: 428 },
  { name: "Skuntank",    id: 435 },
  { name: "Bronzong",    id: 437 },
  { name: "Munchlax",    id: 446 },
  { name: "Drapion",     id: 452 },
  { name: "Abomasnow",   id: 460 },
  { name: "Froslass",    id: 478 },
  { name: "Rotom",       id: 479 },
  { name: "Stoutland",   id: 508 },
  { name: "Liepard",     id: 510 },
  { name: "Musharna",    id: 518 },
  { name: "Unfezant",    id: 521 },
  { name: "Boldore",     id: 525 },
  { name: "Swoobat",     id: 528 },
  { name: "Audino",      id: 531 },
  { name: "Gurdurr",     id: 533 },
  { name: "Palpitoad",   id: 536 },
  { name: "Seismitoad",  id: 537 },
  { name: "Scolipede",   id: 545 },
  { name: "Whimsicott",  id: 547 },
  { name: "Lilligant",   id: 549 },
  { name: "Basculin",    id: 550 },
  { name: "Krookodile",  id: 553 },
  { name: "Maractus",    id: 556 },
  { name: "Crustle",     id: 558 },
  { name: "Sigilyph",    id: 561 },
  { name: "Cofagrigus",  id: 563 },
  { name: "Garbodor",    id: 569 },
  { name: "Cinccino",    id: 573 },
  { name: "Vanillish",   id: 583 },
  { name: "Emolga",      id: 587 },
  { name: "Escavalier",  id: 589 },
  { name: "Amoonguss",   id: 591 },
  { name: "Jellicent",   id: 593 },
  { name: "Galvantula",  id: 596 },
  { name: "Klang",       id: 600 },
  { name: "Klinklang",   id: 601 },
  { name: "Beheeyem",    id: 606 },
  { name: "Lampent",     id: 608 },
  { name: "Fraxure",     id: 611 },
  { name: "Beartic",     id: 614 },
  { name: "Cryogonal",   id: 615 },
  { name: "Accelgor",    id: 617 },
  { name: "Stunfisk",    id: 618 },
  { name: "Mienshao",    id: 620 },
  { name: "Druddigon",   id: 621 },
  { name: "Golurk",      id: 623 },
  { name: "Bisharp",     id: 625 },
  { name: "Bouffalant",  id: 626 },
  { name: "Heatmor",     id: 631 },
  { name: "Durant",      id: 632 },
  { name: "Diggersby",   id: 659 },
  { name: "Talonflame",  id: 663 },
  { name: "Pangoro",     id: 675 },
  { name: "Doublade",    id: 680 },
  { name: "Malamar",     id: 687 },
  { name: "Barbaracle",  id: 689 },
  { name: "Heliolisk",   id: 695 },
  { name: "Tyrantrum",   id: 697 },
  { name: "Aurorus",     id: 699 },
  { name: "Hawlucha",    id: 701 },
];

function spriteUrl(id) {
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/${id}.png`;
}
